include: package:very_good_analysis/analysis_options.yaml
#include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    prefer_if_elements_to_conditional_expressions: false
    one_member_abstracts: false
    no_default_cases: false

#    - prefer_single_quotes
#    - always_use_package_imports
#    - package_names
#    - require_trailing_commas
#    - lines_longer_than_80_chars

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  # https://github.com/rrouselGit/freezed/issues/488#issuecomment-894358980
  errors:
    invalid_annotation_target: ignore
